spring:
  application:
    name: project-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:1991/project-db
    username: postgres
    password: 1991
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

server:
  port: 8082

keycloak:
  realm: cydeo-dev
  auth-server-url: http://localhost:8080/auth
  ssl-required: none
  resource: ticketing-app
  credentials:
    secret: Yg92eAjU2NfiJWaLl8CieEbQdv55VGpL
  use-resource-role-mappings: true
  bearer-only: true

master:
  user:
    username: admin
    password: admin
  realm: master
  client: master-client


eureka:
  instance:
    preferIpAddress: true
    ipAddress: 127.0.0.1 localhost
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health

  client:
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/ # This is where a eureka client sends the information to eureka server to register themself


management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
  context-path: http://localhost:${server.port}/actuator


info:
  application:
    name: project-service
    description: Ticketing Application Project Service
